### ISSUE TITLE
Создай модель и менеджер пользователей

### ISSUE THREAD

**Issue by MironBerch** [Ventel1555/distance-education-platform#1]
# Создай модель пользователя наследуй свою модель от AbstractBaseUser и используй PermissionsMixin, а так-же напиши менеджер пользователей воспользовавшись BaseUserManager.
Получишь более гибкую модель пользователя. Но тебе будет необходимо написать свой менеджер пользователей. Не беспокойся тебе это очень сильно окупиться. А свой менеджер тебе придётся в любом случае писать.

**Comment by vladvikhrov** [comment]
Спасибо большое вам за советы! Приму на сведение, а вообще, сер, не душните так сильно, умничаешь как ишак

**Comment by vladvikhrov** [comment]
Ку, я сделал как ты и говрил. Пока с полями есть не точность (это тз просто имба), а так смотри последний комит.
